spring:
  application:
    name: products-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
   # url: jdbc:mysql://db:3306/products_db?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/db_products-service?serverTimezone=UTC
    password:
    username: root
eureka:
  client:
    service-url.defaultZone: http://eureka-server:8761/eureka


server:
  port: 8081
